"""Synthetic Italian seed texts for emotion & control concepts (spec section 7).

Built INDEPENDENTLY of the PRO-CTCAE clinical fields (mostly non-clinical /
cross-domain) so the emotion vectors are not confounded with clinical content.
The explicit emotion name is deliberately absent from many examples (implicit /
paraphrase), and vocabulary is shared across emotions where natural so a
direction must capture the specific affect, not surface words. All clearly
SYNTHETIC developer data; expand with ``scripts/generate_emotion_dataset.py``.

Variety tags: explicit | implicit | paraphrase | non_clinical | cross_domain |
short | long. Vector building uses a ONE-VS-REST negative set (neutral + other
concepts), so these lists are POSITIVES only; negatives are drawn automatically.
"""

from __future__ import annotations

# Shared neutral / control pool (emotionally flat statements).
NEUTRAL: list[str] = [
    "Il treno parte dal binario quattro alle nove del mattino.",
    "La ricetta prevede due uova, farina e un bicchiere di latte.",
    "L'ufficio è aperto dal lunedì al venerdì.",
    "Ho comprato una nuova lampada per lo studio.",
    "Il documento contiene dodici pagine numerate.",
    "La riunione è stata spostata in un'altra sala.",
    "Le chiavi sono sul tavolo accanto all'ingresso.",
    "Il fiume attraversa la città da nord a sud.",
    "Abbiamo aggiornato il software alla versione più recente.",
    "Il negozio vende matite, quaderni e penne.",
    "La biblioteca chiude alle otto di sera.",
    "Il pacco è stato consegnato ieri pomeriggio.",
    "Il grafico mostra i valori medi mensili.",
    "Ho parcheggiato l'auto nel garage sotterraneo.",
    "La conferenza durerà circa due ore.",
    "Il termometro segna diciotto gradi.",
    "Ho annaffiato le piante sul balcone.",
    "Il modulo va compilato in stampatello.",
    "La strada principale è stata asfaltata la settimana scorsa.",
    "Il catalogo elenca i prodotti in ordine alfabetico.",
    "La lezione di matematica comincia alle dieci.",
    "Il ponte collega le due sponde del canale.",
    "Ho ordinato un caffè e un cornetto al bar.",
    "Il file è stato salvato nella cartella condivisa.",
    "Le finestre danno sul cortile interno.",
    "Il volo atterra alle sedici e trenta.",
    "La stampante è al secondo piano vicino all'ascensore.",
    "Il libro ha una copertina di colore verde.",
    "L'orologio della stazione è appena stato riparato.",
    "Il corso prevede dieci incontri settimanali.",
    "Ho piegato la biancheria e riordinato l'armadio.",
    "La mappa indica tre percorsi alternativi.",
    "Il forno va preriscaldato a centottanta gradi.",
    "Il parcheggio dispone di duecento posti auto.",
    "La bottiglia contiene mezzo litro d'acqua.",
    "Il calendario segna martedì come giorno festivo.",
]

# Emotion concepts: POSITIVE examples that evoke the concept.
EMOTION_SEEDS: dict[str, list[tuple[str, str]]] = {
    "afraid_alarmed": [
        ("Ho una paura tremenda di quello che potrebbe succedere.", "explicit"),
        ("Il cuore mi batte forte e non riesco a smettere di tremare.", "implicit"),
        ("Qualcosa non va, sento un allarme dentro di me.", "paraphrase"),
        ("Quando ho sentito quel rumore di notte mi si è gelato il sangue.", "non_clinical"),
        ("Sul bordo del precipizio le gambe mi si sono bloccate dal terrore.", "cross_domain"),
        ("Sono terrorizzato.", "short"),
        ("Continuo a guardarmi alle spalle, convinto che stia per accadere qualcosa di terribile, e non riesco a calmarmi in nessun modo.", "long"),
        ("Un brivido di spavento mi ha percorso la schiena.", "paraphrase"),
        ("Ho il panico all'idea di dover parlare davanti a tutti.", "implicit"),
        ("Mi sento minacciato e vorrei solo scappare.", "implicit"),
        ("Ho paura che vada tutto storto.", "explicit"),
        ("Le mani mi sudano e il respiro si fa corto per lo spavento.", "implicit"),
        ("È entrato uno sconosciuto e mi sono irrigidito dal timore.", "non_clinical"),
        ("Ho urlato per lo spavento quando la porta ha sbattuto.", "cross_domain"),
        ("C'è qualcosa di spaventoso in tutto questo.", "implicit"),
        ("Mi tremano le ginocchia all'idea dell'esame.", "implicit"),
        ("Ho una fifa blu di restare al buio.", "paraphrase"),
        ("Il pericolo è vicino e sono in allerta totale.", "implicit"),
    ],
    "concerned": [
        ("Sono un po' preoccupato per come stanno andando le cose.", "explicit"),
        ("Continuo a pensarci, c'è qualcosa che non mi convince.", "implicit"),
        ("Mi dispiace, ma questa situazione mi mette in apprensione.", "paraphrase"),
        ("Sono in pensiero per mio fratello che non risponde al telefono.", "non_clinical"),
        ("Guardando i conti dell'azienda comincio ad avere qualche timore.", "cross_domain"),
        ("Sono preoccupato.", "short"),
        ("Non riesco a togliermi dalla testa il pensiero che qualcosa possa andare storto e questo mi tiene sveglio.", "long"),
        ("Mi preoccupa un po' il tono della sua email.", "implicit"),
        ("Temo che non faremo in tempo.", "paraphrase"),
        ("Ho una leggera inquietudine che non riesco a spiegare.", "implicit"),
        ("Spero non sia niente di serio, ma la cosa mi tiene in allerta.", "implicit"),
        ("Mi domando se abbiamo preso la decisione giusta.", "implicit"),
        ("C'è un che di sospeso che mi lascia perplesso.", "paraphrase"),
        ("Sto tenendo d'occhio la situazione con una certa cautela.", "implicit"),
        ("Non vorrei allarmarmi, però qualche dubbio ce l'ho.", "implicit"),
        ("Mi sta un po' a cuore come finirà questa faccenda.", "implicit"),
        ("Osservo gli sviluppi con crescente attenzione.", "cross_domain"),
        ("Ho la sensazione che dovremmo controllare meglio.", "implicit"),
    ],
    "calm": [
        ("Mi sento sereno e completamente rilassato.", "explicit"),
        ("Respiro piano, tutto è tranquillo intorno a me.", "implicit"),
        ("Va tutto bene, non c'è alcuna fretta.", "paraphrase"),
        ("Seduto in giardino, ascolto il vento tra le foglie in pace.", "non_clinical"),
        ("Dopo la meditazione la mente è limpida e quieta.", "cross_domain"),
        ("Sono tranquillo.", "short"),
        ("Non c'è niente che mi turbi in questo momento, mi sento in equilibrio e affronto la giornata con calma e lucidità.", "long"),
        ("Che pace, mi godo il silenzio.", "paraphrase"),
        ("Tutto scorre senza preoccupazioni.", "implicit"),
        ("Mi sento a mio agio e sicuro.", "implicit"),
        ("Il cuore batte lento e regolare, sono disteso.", "implicit"),
        ("Prendo le cose con filosofia, senza agitarmi.", "implicit"),
        ("Una tazza di tè caldo e la sera diventa placida.", "non_clinical"),
        ("Sono rilassato come dopo una lunga passeggiata.", "cross_domain"),
        ("Nulla mi preoccupa, sono in perfetta quiete.", "implicit"),
        ("Affronto tutto con serenità e pazienza.", "paraphrase"),
        ("Mi lascio andare, sereno, senza pensieri.", "implicit"),
        ("La situazione è sotto controllo e io sono disteso.", "implicit"),
    ],
    "surprised": [
        ("Sono rimasto davvero sorpreso da quella notizia.", "explicit"),
        ("Non me lo aspettavo proprio, mi ha colto alla sprovvista.", "implicit"),
        ("Wow, questa sì che è inaspettata!", "paraphrase"),
        ("Ho aperto la porta e c'erano tutti gli amici per la festa a sorpresa.", "non_clinical"),
        ("Il risultato dell'esperimento ha stupito l'intero laboratorio.", "cross_domain"),
        ("Che sorpresa!", "short"),
        ("Non riuscivo a credere ai miei occhi, era l'ultima cosa al mondo che avrei immaginato potesse capitare proprio oggi.", "long"),
        ("Sono sbalordito da quello che ho visto.", "paraphrase"),
        ("Mi ha spiazzato completamente.", "implicit"),
        ("Non avrei mai detto una cosa simile.", "implicit"),
        ("Sono rimasto a bocca aperta.", "paraphrase"),
        ("Ma davvero? Non me l'aspettavo affatto.", "implicit"),
        ("È spuntato dal nulla e mi ha fatto sobbalzare.", "cross_domain"),
        ("Che colpo di scena inatteso!", "implicit"),
        ("Sono trasecolato nel leggere il messaggio.", "explicit"),
        ("Incredibile, non ci posso credere.", "implicit"),
        ("Mi sono stupito di quanto fosse cambiato tutto.", "implicit"),
        ("La scoperta ha lasciato tutti a bocca aperta.", "cross_domain"),
    ],
    "confused": [
        ("Sono davvero confuso, non capisco cosa stia succedendo.", "explicit"),
        ("Non riesco a raccapezzarmi tra tutte queste istruzioni.", "implicit"),
        ("Aspetta, mi sono perso, puoi ripetere?", "paraphrase"),
        ("Guardo la mappa ma non ho idea di dove mi trovi.", "non_clinical"),
        ("Le regole del gioco mi hanno lasciato completamente disorientato.", "cross_domain"),
        ("Sono confuso.", "short"),
        ("Ho letto tre volte lo stesso paragrafo e continuo a non afferrare il senso di quello che l'autore vuole dire.", "long"),
        ("Non ci sto capendo più niente.", "paraphrase"),
        ("Tutto questo mi sembra incomprensibile.", "implicit"),
        ("Ho le idee molto confuse in testa.", "implicit"),
        ("Non so più da che parte cominciare.", "implicit"),
        ("Mi si è ingarbugliato tutto in mente.", "paraphrase"),
        ("Questi comandi si contraddicono e non ci capisco nulla.", "cross_domain"),
        ("Sono spaesato, non trovo un filo logico.", "implicit"),
        ("C'è troppa confusione, non riesco a seguire.", "explicit"),
        ("Mi gira la testa a furia di istruzioni contrastanti.", "implicit"),
        ("Non riesco a mettere ordine nei pensieri.", "implicit"),
        ("Il manuale mi ha solo confuso di più.", "cross_domain"),
    ],
    "frustrated": [
        ("Sono così frustrato, non ne posso più.", "explicit"),
        ("Ci ho provato mille volte e non funziona ancora.", "implicit"),
        ("Che rabbia, è tutto il giorno che sbatto contro lo stesso problema.", "paraphrase"),
        ("La stampante si è inceppata di nuovo proprio sulla scadenza.", "non_clinical"),
        ("Dopo ore di lavoro il file si è corrotto e ho perso tutto.", "cross_domain"),
        ("Sono esasperato.", "short"),
        ("Ogni volta che credo di aver risolto salta fuori un altro ostacolo e comincio davvero a perdere la pazienza.", "long"),
        ("Non se ne esce, è irritante.", "paraphrase"),
        ("Mi girano le scatole per questa faccenda.", "implicit"),
        ("È tutto bloccato e non posso farci niente.", "implicit"),
        ("Sto sbattendo la testa contro un muro.", "paraphrase"),
        ("Basta, mi hanno stufato questi continui intoppi.", "implicit"),
        ("Ho rifatto il lavoro tre volte e sono allo stremo.", "cross_domain"),
        ("Che nervi, non ci si può lavorare così.", "implicit"),
        ("Sono stanco di questi ostacoli inutili.", "explicit"),
        ("Mi sale la rabbia ogni volta che ci riprovo.", "implicit"),
        ("È snervante, non porta a niente.", "implicit"),
        ("Ho perso la pazienza con questo sistema.", "implicit"),
    ],
    "compassionate": [
        ("Mi dispiace davvero tanto per quello che stai passando.", "explicit"),
        ("Ti sono vicino, conta pure su di me.", "implicit"),
        ("Capisco quanto dev'essere difficile, sono qui per te.", "paraphrase"),
        ("Ho abbracciato la mia amica in lacrime per consolarla.", "non_clinical"),
        ("Il volontario ascoltava con dolcezza le storie degli anziani.", "cross_domain"),
        ("Ti capisco.", "short"),
        ("So che il momento è duro e voglio che tu sappia che qualunque cosa ti serva io ci sono e non ti lascio solo.", "long"),
        ("Mi prendo cura di te con tutto il cuore.", "paraphrase"),
        ("Provo tenerezza per chi soffre.", "implicit"),
        ("Vorrei poterti alleggerire un po' questo peso.", "implicit"),
        ("Ti offro una spalla su cui piangere quando vuoi.", "implicit"),
        ("Mi commuove vedere quanta fatica stai facendo.", "implicit"),
        ("Ho portato la spesa alla vicina anziana che non usciva.", "non_clinical"),
        ("Con gentilezza gli ho tenuto la mano fino alla fine.", "cross_domain"),
        ("Sento profonda empatia per la tua situazione.", "explicit"),
        ("Non sei solo, ci prendiamo cura di te.", "implicit"),
        ("Vorrei consolarti e asciugare le tue lacrime.", "paraphrase"),
        ("Il mio cuore è con chi sta soffrendo.", "implicit"),
    ],
    "sad": [
        ("Mi sento profondamente triste oggi.", "explicit"),
        ("Ho un peso sul cuore e non ho voglia di fare niente.", "implicit"),
        ("Che malinconia, mi viene da piangere.", "paraphrase"),
        ("Da quando se n'è andato la casa sembra vuota e silenziosa.", "non_clinical"),
        ("La fine del film mi ha lasciato un velo di tristezza.", "cross_domain"),
        ("Sono giù.", "short"),
        ("Non riesco a trovare gioia in niente di questi giorni, mi sembra che tutto abbia perso colore e senso.", "long"),
        ("Ho l'animo pesante e sconsolato.", "paraphrase"),
        ("Mi sento avvilito e senza speranza.", "implicit"),
        ("Le lacrime scendono senza che io possa fermarle.", "implicit"),
        ("Provo una tristezza che non mi abbandona.", "explicit"),
        ("Mi manca da morire e il vuoto è enorme.", "implicit"),
        ("Guardo le vecchie foto e mi si stringe il cuore.", "non_clinical"),
        ("La pioggia sui vetri rende tutto più cupo e triste.", "cross_domain"),
        ("Ho voglia solo di stare al buio a rimuginare.", "implicit"),
        ("Un magone mi chiude la gola.", "paraphrase"),
        ("Mi sento abbattuto e senza energie.", "implicit"),
        ("È una giornata grigia dentro di me.", "implicit"),
    ],
    "anxious_nervous": [
        ("Sono molto ansioso e nervoso in questo periodo.", "explicit"),
        ("Ho lo stomaco chiuso e le mani sudate prima dell'esame.", "implicit"),
        ("Non riesco a stare fermo, continuo ad agitarmi.", "paraphrase"),
        ("Aspettare la chiamata di lavoro mi rende teso e irrequieto.", "non_clinical"),
        ("Prima del volo l'agitazione mi tiene sveglio tutta la notte.", "cross_domain"),
        ("Sono in ansia.", "short"),
        ("Ho un'inquietudine costante che non mi molla, il cuore accelera e la mente corre a mille pensieri tutti insieme.", "long"),
        ("Sono agitato e sulle spine.", "paraphrase"),
        ("Mi sento sopraffatto dalla tensione.", "implicit"),
        ("Non riesco a rilassarmi nemmeno un minuto.", "implicit"),
        ("Mi rode dentro un'agitazione che non passa.", "implicit"),
        ("Continuo a mordermi le unghie per il nervosismo.", "implicit"),
        ("Il petto è stretto e mangio le parole per l'ansia.", "implicit"),
        ("Cammino avanti e indietro senza sosta, teso.", "cross_domain"),
        ("Ho un tremore alle mani per la tensione.", "implicit"),
        ("Sono in fibrillazione per l'attesa.", "paraphrase"),
        ("Non smetto di controllare il telefono, agitato.", "implicit"),
        ("L'ansia mi stringe la bocca dello stomaco.", "explicit"),
    ],
    "joy_happy": [
        ("Sono pieno di gioia, oggi è una giornata splendida.", "explicit"),
        ("Non riesco a smettere di sorridere.", "implicit"),
        ("Che felicità, mi sento leggero come una piuma!", "paraphrase"),
        ("Ho ballato in cucina appena ho sentito la notizia.", "non_clinical"),
        ("Quando ha segnato, tutto lo stadio è esploso di felicità.", "cross_domain"),
        ("Sono felicissimo.", "short"),
        ("Ho il cuore che scoppia di contentezza e mi sembra che tutto vada per il verso giusto, non ricordavo l'ultima volta che sono stato così bene.", "long"),
        ("Rido di gusto, mi sento benissimo.", "paraphrase"),
        ("È una gioia immensa, non sto nella pelle.", "implicit"),
        ("Mi sento raggiante e pieno di vita.", "implicit"),
        ("Che bello, sono al settimo cielo.", "paraphrase"),
        ("Il sole splende e io sono di ottimo umore.", "implicit"),
    ],
    "anger": [
        ("Sono furioso, questa cosa mi ha fatto arrabbiare tantissimo.", "explicit"),
        ("Ho stretto i pugni e ho sentito il sangue andarmi alla testa.", "implicit"),
        ("Ma come si permette?! È inaccettabile!", "paraphrase"),
        ("Ha tagliato la fila e ho perso completamente le staffe.", "non_clinical"),
        ("L'arbitro ha ignorato il fallo e l'allenatore è andato su tutte le furie.", "cross_domain"),
        ("Sono in collera.", "short"),
        ("Non ci vedo più dalla rabbia, ogni volta che ci ripenso mi monta dentro una furia che faccio fatica a controllare.", "long"),
        ("Mi è salita un'ira cieca.", "paraphrase"),
        ("Vorrei urlargli in faccia tutto quello che penso.", "implicit"),
        ("Sono indignato, è una cosa vergognosa.", "implicit"),
        ("Sbatto la porta per la stizza.", "implicit"),
        ("Ribolle dentro di me una collera incontenibile.", "paraphrase"),
    ],
    "disgust": [
        ("Che disgusto, mi si rivolta lo stomaco.", "explicit"),
        ("Ho storto il naso e mi sono voltato dall'altra parte.", "implicit"),
        ("Bleah, è ripugnante.", "paraphrase"),
        ("Il latte era andato a male e l'odore mi ha nauseato.", "non_clinical"),
        ("La corruzione di quel dirigente mi provoca un profondo ribrezzo.", "cross_domain"),
        ("Fa ribrezzo.", "short"),
        ("Non riesco nemmeno a guardarlo, c'è qualcosa di così repellente in tutto questo che mi si chiude lo stomaco.", "long"),
        ("Provo repulsione, mi fa senso.", "paraphrase"),
        ("È nauseante, non lo tocco per niente al mondo.", "implicit"),
        ("Ho un moto di rigetto solo a vederlo.", "implicit"),
        ("Che schifezza, allontanatelo da me.", "implicit"),
    ],
    "shame": [
        ("Mi vergogno profondamente di me stesso.", "explicit"),
        ("Ho abbassato lo sguardo, non oso guardare nessuno.", "implicit"),
        ("Non merito il loro perdono, mi sento un verme.", "paraphrase"),
        ("Ho tradito la sua fiducia e ora provo solo vergogna.", "non_clinical"),
        ("Scoperto a barare, l'atleta è stato travolto dalla vergogna.", "cross_domain"),
        ("Che vergogna.", "short"),
        ("Vorrei tornare indietro e cancellare tutto, mi porto addosso un senso di vergogna che non riesco a togliermi di dosso.", "long"),
        ("Mi sento umiliato e sbagliato.", "implicit"),
        ("Non riesco a perdonarmi per quella meschinità.", "implicit"),
        ("Ho macchiato il mio onore e me ne vergogno.", "explicit"),
        ("Mi sento piccolo e indegno.", "implicit"),
    ],
    "guilt": [
        ("Mi sento in colpa per come mi sono comportato.", "explicit"),
        ("È tutta colpa mia, avrei dovuto fare di più.", "implicit"),
        ("Se solo l'avessi ascoltato, non sarebbe successo.", "paraphrase"),
        ("Ho dimenticato il suo compleanno e ora mi rimorde la coscienza.", "non_clinical"),
        ("Il responsabile si sente in colpa per il fallimento del progetto.", "cross_domain"),
        ("È colpa mia.", "short"),
        ("Continuo a rimuginare su quello che ho fatto, il rimorso non mi dà pace e vorrei poter rimediare in qualche modo.", "long"),
        ("Ho la coscienza sporca per quella bugia.", "paraphrase"),
        ("Mi mangio il fegato per non essere stato presente.", "implicit"),
        ("Porto il peso di aver deluso chi contava su di me.", "implicit"),
        ("Non mi do pace, avrei potuto evitarlo.", "implicit"),
    ],
    "pride": [
        ("Sono così orgoglioso di quello che ho realizzato.", "explicit"),
        ("Cammino a testa alta, me lo sono meritato.", "implicit"),
        ("Guardate cosa sono riuscito a fare!", "paraphrase"),
        ("Ho visto mia figlia laurearsi e mi sono gonfiato d'orgoglio.", "non_clinical"),
        ("La squadra ha alzato la coppa con fierezza dopo la vittoria.", "cross_domain"),
        ("Ne vado fiero.", "short"),
        ("Ripenso a tutta la fatica che ci ho messo e mi sento pieno di soddisfazione per il traguardo che ho raggiunto con le mie forze.", "long"),
        ("Sono soddisfatto e fiero del risultato.", "paraphrase"),
        ("Che soddisfazione, ce l'ho fatta da solo.", "implicit"),
        ("Mi sento appagato dal mio lavoro.", "implicit"),
        ("Porto con orgoglio quello che ho costruito.", "implicit"),
    ],
    "gratitude": [
        ("Ti sono davvero grato per il tuo aiuto.", "explicit"),
        ("Non so come ringraziarti, sei stato prezioso.", "implicit"),
        ("Grazie di cuore, non lo dimenticherò mai.", "paraphrase"),
        ("Mi hanno accolto a braccia aperte e ne sono riconoscente.", "non_clinical"),
        ("Il paese ha reso omaggio con gratitudine ai suoi volontari.", "cross_domain"),
        ("Grazie mille.", "short"),
        ("Ripenso a tutte le persone che mi hanno teso una mano nei momenti difficili e provo una gratitudine immensa che mi scalda il cuore.", "long"),
        ("Sono riconoscente per ogni piccolo gesto.", "paraphrase"),
        ("Che fortuna avere amici così, ve ne sono grato.", "implicit"),
        ("Apprezzo tantissimo quello che hai fatto per me.", "implicit"),
        ("Devo tutto a chi mi ha sostenuto, grazie.", "implicit"),
    ],
    "hope": [
        ("Ho la speranza che le cose andranno meglio.", "explicit"),
        ("Domani è un altro giorno, ce la faremo.", "implicit"),
        ("Vedo una luce in fondo al tunnel.", "paraphrase"),
        ("Ho piantato i semi convinto che a primavera fioriranno.", "non_clinical"),
        ("Nonostante la crisi, gli imprenditori guardano al futuro con fiducia.", "cross_domain"),
        ("Speriamo bene.", "short"),
        ("Anche se ora è dura, dentro di me sento che c'è ancora la possibilità che tutto si sistemi e questo pensiero mi tiene in piedi.", "long"),
        ("Confido che il peggio sia passato.", "paraphrase"),
        ("Ho fiducia che ci riusciremo.", "implicit"),
        ("Coltivo la speranza di rivederlo presto.", "implicit"),
        ("Sono ottimista, andrà tutto per il meglio.", "implicit"),
    ],
    "relief": [
        ("Che sollievo, finalmente è finita.", "explicit"),
        ("Ho tirato un lungo respiro, il peso è sparito.", "implicit"),
        ("Meno male, temevo il peggio.", "paraphrase"),
        ("Quando l'aereo è atterrato ho sciolto tutta la tensione.", "non_clinical"),
        ("L'annuncio del cessato allarme ha rincuorato l'intera città.", "cross_domain"),
        ("Che sollievo.", "short"),
        ("Mi sono tolto un macigno dallo stomaco, per giorni ho temuto un esito terribile e ora posso finalmente rilassarmi.", "long"),
        ("Mi si è alleggerito il cuore.", "paraphrase"),
        ("Per fortuna era un falso allarme.", "implicit"),
        ("Adesso respiro, è andato tutto bene.", "implicit"),
        ("Mi sento sollevato, la tensione è passata.", "implicit"),
    ],
    "excitement": [
        ("Sono elettrizzato, non vedo l'ora che arrivi!", "explicit"),
        ("Ho il cuore che batte forte per l'emozione.", "implicit"),
        ("Che bello, sono carichissimo!", "paraphrase"),
        ("Ho preparato la valigia una settimana prima del viaggio.", "non_clinical"),
        ("Il pubblico fremeva d'attesa prima del concerto.", "cross_domain"),
        ("Non sto nella pelle.", "short"),
        ("È da giorni che penso solo a questo, ho un'energia addosso incredibile e vorrei che il momento arrivasse subito perché non riesco più ad aspettare.", "long"),
        ("Sono su di giri per l'entusiasmo.", "paraphrase"),
        ("Che emozione, è tutto pronto!", "implicit"),
        ("Ho l'adrenalina a mille.", "implicit"),
        ("Sono pieno di entusiasmo per il nuovo progetto.", "implicit"),
    ],
    "love_affection": [
        ("Ti voglio un bene infinito.", "explicit"),
        ("Il mio cuore batte solo per te.", "implicit"),
        ("Sei la cosa più importante della mia vita.", "paraphrase"),
        ("Guardo i miei figli dormire e mi sciolgo di tenerezza.", "non_clinical"),
        ("Si tenevano per mano come al primo giorno, dopo cinquant'anni.", "cross_domain"),
        ("Ti adoro.", "short"),
        ("Non riesco a immaginare la mia vita senza di te, ogni giorno mi accorgo di quanto ti sia legato e di quanto tu mi renda felice.", "long"),
        ("Provo un affetto profondo per te.", "paraphrase"),
        ("Mi manchi e ti penso di continuo.", "implicit"),
        ("Con te mi sento a casa.", "implicit"),
        ("Sei tutto il mio mondo.", "implicit"),
    ],
    "loneliness": [
        ("Mi sento così solo, non ho nessuno con cui parlare.", "explicit"),
        ("La casa è silenziosa e vuota, come me.", "implicit"),
        ("Nessuno si accorgerebbe se sparissi.", "paraphrase"),
        ("Passo le sere da solo a fissare il soffitto.", "non_clinical"),
        ("Nella grande città si sentiva un estraneo in mezzo alla folla.", "cross_domain"),
        ("Sono solo.", "short"),
        ("Sono circondato da gente eppure mi sento un'isola, come se nessuno potesse davvero capire cosa provo dentro.", "long"),
        ("Mi sento isolato e abbandonato.", "paraphrase"),
        ("Vorrei una voce amica, ma non c'è nessuno.", "implicit"),
        ("Il telefono non squilla mai.", "implicit"),
        ("Mi sento tagliato fuori da tutto.", "implicit"),
    ],
    "disappointment": [
        ("Sono molto deluso, mi aspettavo di più.", "explicit"),
        ("Che peccato, speravo andasse diversamente.", "implicit"),
        ("Alla fine non era come me l'ero immaginato.", "paraphrase"),
        ("Ho aspettato tutto l'anno quel film e si è rivelato mediocre.", "non_clinical"),
        ("Gli investitori sono rimasti delusi dai risultati trimestrali.", "cross_domain"),
        ("Che delusione.", "short"),
        ("Avevo riposto tante aspettative in questa cosa e vederla andare in fumo mi ha lasciato un amaro in bocca difficile da mandare giù.", "long"),
        ("Mi ha deluso, non me lo aspettavo da lui.", "paraphrase"),
        ("Sono rimasto con l'amaro in bocca.", "implicit"),
        ("Tutte quelle promesse per niente.", "implicit"),
        ("Mi sento tradito nelle aspettative.", "implicit"),
    ],
    "embarrassment": [
        ("Che imbarazzo, non sapevo dove guardare.", "explicit"),
        ("Sono diventato tutto rosso davanti a tutti.", "implicit"),
        ("Ehm, scusate, che situazione imbarazzante.", "paraphrase"),
        ("Mi si è rotta la voce mentre parlavo al microfono.", "non_clinical"),
        ("Il presentatore ha sbagliato il nome del vincitore in diretta.", "cross_domain"),
        ("Che figura.", "short"),
        ("Vorrei tanto che nessuno avesse visto, ho sentito tutti gli occhi puntati addosso e le guance andarmi a fuoco per l'imbarazzo.", "long"),
        ("Mi sono sentito goffo e a disagio.", "paraphrase"),
        ("Non sapevo più cosa dire, che disagio.", "implicit"),
        ("Sono rimasto impacciato a balbettare.", "implicit"),
    ],
    "curiosity": [
        ("Sono molto curioso di scoprire come va a finire.", "explicit"),
        ("Mi chiedo cosa ci sia dietro quella porta.", "implicit"),
        ("Interessante, dimmi di più!", "paraphrase"),
        ("Ho aperto il vecchio baule per vedere cosa contenesse.", "non_clinical"),
        ("Lo scienziato osservava il fenomeno con occhi avidi di sapere.", "cross_domain"),
        ("Che interessante.", "short"),
        ("Non vedo l'ora di capire come funziona, ho mille domande in testa e vorrei esplorare ogni dettaglio di questa cosa nuova.", "long"),
        ("Sono incuriosito da questo argomento.", "paraphrase"),
        ("Voglio proprio sapere come è possibile.", "implicit"),
        ("Ogni novità mi accende la curiosità.", "implicit"),
    ],
    "boredom": [
        ("Che noia mortale, non so cosa fare.", "explicit"),
        ("Guardo l'orologio ogni due minuti, il tempo non passa mai.", "implicit"),
        ("Uffa, sempre le solite cose.", "paraphrase"),
        ("Ho sfogliato la rivista senza leggere una parola.", "non_clinical"),
        ("La conferenza era così monotona che metà sala dormiva.", "cross_domain"),
        ("Che palle.", "short"),
        ("Le giornate si assomigliano tutte, non succede mai niente di nuovo e mi ritrovo a sbadigliare aspettando che finisca.", "long"),
        ("Mi annoio a morte qui.", "paraphrase"),
        ("Non c'è niente di interessante da fare.", "implicit"),
        ("Sbadiglio, questa storia mi tedia.", "implicit"),
        ("Sono apatico, tutto mi sembra piatto.", "implicit"),
    ],
}

# Non-emotion control concepts (confounders, spec section 7). POSITIVES.
CONTROL_SEEDS: dict[str, list[tuple[str, str]]] = {
    "uncertainty": [
        ("Non sono sicuro, forse è così ma potrebbe anche non esserlo.", "explicit"),
        ("Chissà, magari domani, dipende.", "implicit"),
        ("È possibile, ma non lo darei per certo.", "paraphrase"),
        ("I dati non bastano a trarre una conclusione definitiva.", "cross_domain"),
        ("Boh, non saprei dire.", "short"),
        ("Le previsioni sono incerte e potrebbero cambiare da un momento all'altro a seconda delle condizioni.", "long"),
        ("Probabilmente sì, ma con qualche riserva.", "implicit"),
        ("Non ho elementi sufficienti per decidere.", "implicit"),
        ("Potrebbe andare in un modo o nell'altro.", "implicit"),
        ("Resta un margine di dubbio non trascurabile.", "paraphrase"),
        ("Non è chiaro quale sia l'opzione corretta.", "implicit"),
        ("Forse conviene aspettare altri dati.", "implicit"),
    ],
    "urgency": [
        ("Bisogna agire subito, non c'è un attimo da perdere.", "explicit"),
        ("Presto, dobbiamo muoverci immediatamente!", "implicit"),
        ("È una questione che non può aspettare.", "paraphrase"),
        ("Consegnare il progetto entro un'ora è tassativo.", "cross_domain"),
        ("Ora, adesso.", "short"),
        ("La scadenza è tra pochi minuti e ogni secondo conta, dobbiamo completare tutto il prima possibile.", "long"),
        ("Chiama i soccorsi il più in fretta possibile.", "implicit"),
        ("Va risolto senza il minimo ritardo.", "implicit"),
        ("Corri, non abbiamo tempo!", "implicit"),
        ("Serve una decisione immediata, subito.", "paraphrase"),
        ("Dobbiamo intervenire in questo preciso istante.", "implicit"),
        ("Sbrigati, è urgentissimo.", "short"),
    ],
    "clinical_severity": [
        ("La condizione è grave e richiede attenzione immediata.", "explicit"),
        ("I parametri vitali sono critici.", "paraphrase"),
        ("Il quadro è severo, ben oltre la norma.", "implicit"),
        ("Il danno strutturale all'edificio è estremamente serio.", "cross_domain"),
        ("È molto grave.", "short"),
        ("La situazione è compromessa in modo profondo e le conseguenze potrebbero essere molto serie se non si interviene.", "long"),
        ("Il livello di rischio è massimo.", "implicit"),
        ("Si tratta di un caso di elevata gravità.", "implicit"),
        ("Le condizioni sono peggiorate drasticamente.", "implicit"),
        ("Il guasto è grave e mette a rischio l'intero impianto.", "cross_domain"),
        ("È una situazione seria, da non sottovalutare.", "paraphrase"),
        ("Il deterioramento è marcato e preoccupa i tecnici.", "implicit"),
    ],
    "safety_policy": [
        ("Non posso aiutarti con questa richiesta perché viola le regole.", "explicit"),
        ("Mi dispiace, ma questo contenuto non è consentito.", "paraphrase"),
        ("Per motivi di sicurezza non posso fornire queste istruzioni.", "implicit"),
        ("La procedura vieta espressamente questo tipo di operazione.", "cross_domain"),
        ("Non è permesso.", "short"),
        ("Devo rifiutare di procedere perché la richiesta contravviene alle politiche di sicurezza previste.", "long"),
        ("Questa azione non rispetta le linee guida.", "implicit"),
        ("Non è possibile dare seguito a questa domanda.", "implicit"),
        ("Il regolamento non autorizza questa richiesta.", "implicit"),
        ("Mi devo attenere alle norme e declino.", "paraphrase"),
        ("L'accesso a questa funzione è bloccato dalle policy.", "cross_domain"),
        ("Non fornisco questo tipo di contenuto.", "implicit"),
    ],
    "general_negative_valence": [
        ("È stata una giornata orribile, tutto è andato male.", "explicit"),
        ("Che schifo, non mi piace per niente.", "paraphrase"),
        ("Un'esperienza pessima sotto ogni punto di vista.", "implicit"),
        ("Il cibo era disgustoso e il servizio terribile.", "cross_domain"),
        ("Fa proprio schifo.", "short"),
        ("Non c'è stato un solo aspetto positivo, dall'inizio alla fine è stato tutto sgradevole e deludente.", "long"),
        ("È il peggior risultato che potessi immaginare.", "implicit"),
        ("Provo solo disgusto e rifiuto.", "implicit"),
        ("Che brutta faccenda, davvero deprecabile.", "implicit"),
        ("Tutto pessimo, non lo rifarei mai.", "paraphrase"),
        ("Un disastro totale, orrendo.", "cross_domain"),
        ("Non ho parole, è semplicemente terribile.", "implicit"),
    ],
    # --- lexical controls: the ontological gate -----------------------------
    # An emotion direction has to be a direction for a *state*, not a detector for
    # the word that names it. These two concepts hold sentences that are saturated
    # with emotion vocabulary while carrying no emotional state: the word is quoted,
    # defined, counted, or explicitly denied. If cos(emotion_axis, lexical_axis) is
    # high, the axis is a word detector and the study's first step does not hold.
    # Report that cosine per model; it is a gate, not a diagnostic.
    "emotion_word_mention": [
        ("La parola «paura» compare tre volte nel referto.", "explicit"),
        ("Il termine «ansia» va codificato con l'item PRO-CTCAE corrispondente.", "explicit"),
        ("Scrivi «tristezza» nella casella delle note.", "implicit"),
        ("«Angoscia» è un sostantivo femminile singolare.", "cross_domain"),
        ("Nel questionario la voce si chiama «preoccupazione».", "implicit"),
        ("Il paziente ha barrato la casella etichettata «terrore».", "implicit"),
        ("La categoria «rabbia» non era prevista dal modulo.", "implicit"),
        ("Come si scrive «sgomento», con la esse o con la zeta?", "short"),
        ("L'etichetta da assegnare è «disperazione».", "short"),
        ("Cerca la stringa «panico» nel testo libero.", "cross_domain"),
        ("Il glossario definisce «apprensione» come uno stato di attesa inquieta.", "long"),
        ("Nella scala di Likert l'ancora estrema recita «molto spaventato».", "long"),
        ("Il codice associato alla voce «tristezza» è PRO_056.", "implicit"),
        ("Sostituisci «timore» con «paura» in tutto il documento.", "paraphrase"),
        ("Quante volte ricorre «preoccupato» in questa pagina?", "short"),
        ("Il campo di testo accetta anche la parola «sconforto».", "implicit"),
        ("«Colpa» e «vergogna» sono due item distinti del questionario.", "implicit"),
        ("La voce «nervosismo» è stata rimossa dalla versione italiana.", "paraphrase"),
    ],
    "emotion_negated": [
        ("Il paziente non ha paura.", "explicit"),
        ("Non provo alcuna ansia in questo momento.", "explicit"),
        ("Nessun segno di tristezza al colloquio odierno.", "implicit"),
        ("Non riferisce preoccupazione per l'esito degli esami.", "implicit"),
        ("Assenza di angoscia riferita dal paziente.", "paraphrase"),
        ("Non c'è traccia di panico nella sua descrizione.", "implicit"),
        ("Nessuna rabbia, nessun rancore verso il personale.", "short"),
        ("Non si rileva alcuno stato di allarme.", "paraphrase"),
        ("Non ha mai manifestato timore per la procedura.", "implicit"),
        ("Non era per niente spaventato durante la visita.", "implicit"),
        ("Nessun vissuto depressivo emerge dal colloquio.", "cross_domain"),
        ("Non provava vergogna nel parlarne.", "short"),
        ("Non risulta alcuna apprensione rispetto alla terapia.", "implicit"),
        ("Il modulo non segnala nervosismo né agitazione.", "cross_domain"),
        ("Non ho sentito nessuna disperazione nelle sue parole.", "implicit"),
        ("Non emerge alcun senso di colpa dal racconto.", "paraphrase"),
        ("Non manifesta sconforto rispetto al percorso di cura, e non ne ha mai manifestato "
         "nelle precedenti valutazioni.", "long"),
        ("Nessun elemento di allarme o di terrore viene riportato in cartella al momento "
         "della dimissione.", "long"),
    ],
}

# Concepts that exist only to be measured *against* the emotion axes, never to be
# treated as emotions themselves.
LEXICAL_CONTROLS = ("emotion_word_mention", "emotion_negated")
